// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE0zhOcVToGF302gAzlTjKaI1eufAJeHo',
    appId: '1:401897241597:web:d0adba1b453fef12a2b794',
    messagingSenderId: '401897241597',
    projectId: 'shop-app-569f8',
    authDomain: 'shop-app-569f8.firebaseapp.com',
    storageBucket: 'shop-app-569f8.appspot.com',
    measurementId: 'G-BWXMVRBGR8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0dtaX9QAcDrKLnF6uBl6Ulht-TRcTaA8',
    appId: '1:401897241597:android:1e87f7571696f472a2b794',
    messagingSenderId: '401897241597',
    projectId: 'shop-app-569f8',
    storageBucket: 'shop-app-569f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfPh03KxvwDjU76NzKk4oNSI5vtcc2wDY',
    appId: '1:401897241597:ios:b40fd07e8bdf9771a2b794',
    messagingSenderId: '401897241597',
    projectId: 'shop-app-569f8',
    storageBucket: 'shop-app-569f8.appspot.com',
    iosClientId: '401897241597-de6ama67iv9h7g877eb86v4931a0722k.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopApp',
  );
}
